project_id = "urhzbawrkmyfaotocuqk"

[functions.activate-account]
verify_jwt = false

[functions.import-students]
verify_jwt = false

[functions.create-institution-admin]
verify_jwt = false

[functions.delete-institution]
verify_jwt = false
